### ISSUE TITLE
Update Thymeleaf 3 ten-minute migration guide

### ISSUE THREAD

**Issue by dtrunk90** [thymeleaf/thymeleaf#504]
It's necessary to add a `@Bean` annotation to the template engine as well as making it public. Otherwise messages won't getting resolved: https://gist.github.com/seanhinkley/6eab2130ceea857c160b#file-thymeleafconfig-java-L45

Please update the migration guide.

**Comment by jmiguelsamper** [comment]
Fixed on the source code. Thank you very much.

**Comment by dtrunk90** [comment]
In the source code of Thymeleaf Spring Extension? So it's not necessary to add the annotation and make the method public in future releases anymore?

Or in the source code of the website? Cause it's still private and without annotation there: https://github.com/thymeleaf/thymeleaf.github.com/blob/master/doc/articles/thymeleaf3migration.html#L108

**Comment by jmiguelsamper** [comment]
Yes, the source code of the article at https://github.com/thymeleaf/thymeleaf-docs/blob/master/docs/articles/thymeleaf3migration.md

The final HTML is generated automatically from the previous file.

**Comment by dtrunk90** [comment]
I see! Thanks.

**Comment by robvanderboom** [comment]
Hi,  
i added public and @Bean,  But my issue still is there (that it sees the already translated result of the attribute as an expression.  I see now also https://github.com/mxab/thymeleaf-extras-data-attribute/issues/8#issuecomment-222149981 ....

**Comment by danielfernandez** [comment]
Website updated! Thanks @dtrunk90
